Repository f-lab-edu/JBLY, pull requests merged in 2023-02, with the labels that each got.

#3 [#1] 프로젝트 생성
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/flab/jbly/JblyApplication.java
  src/main/resources/application.properties
  src/test/java/com/flab/jbly/JblyApplicationTests.java
Labels: chore

#7 [#6] Mysql DB, Flyway and PR template Setting
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  build.gradle
  src/main/java/com/flab/jbly/domain/user/User.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: chore

#8 [#4] 회원 로그인 기능
  build.gradle
  src/main/java/com/flab/jbly/application/user/LoginService.java
  src/main/java/com/flab/jbly/application/user/command/LoginCommand.java
  src/main/java/com/flab/jbly/application/user/result/LoginResult.java
  src/main/java/com/flab/jbly/domain/user/PasswordEncryption.java
  src/main/java/com/flab/jbly/domain/user/User.java
  src/main/java/com/flab/jbly/domain/user/UserRepository.java
  src/main/java/com/flab/jbly/infrastructure/user/exception/UserPasswordNotMatchedException.java
  src/main/java/com/flab/jbly/infrastructure/user/impl/Encryption.java
  src/main/java/com/flab/jbly/infrastructure/user/jpa/UserJpaRepository.java
  src/main/java/com/flab/jbly/infrastructure/user/jpa/UserRepositoryAdapter.java
  src/main/java/com/flab/jbly/presentation/user/LoginController.java
  src/main/java/com/flab/jbly/presentation/user/request/LoginRequest.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/flab/jbly/infrastructure/impl/EncryptionTest.java
Labels: feat

#19 [#2] 회원 가입 기능
  .gitignore
  build.gradle
  src/main/java/com/flab/jbly/application/command/UserSignUpCommand.java
  src/main/java/com/flab/jbly/application/service/UserService.java
  src/main/java/com/flab/jbly/application/service/UserServiceImpl.java
  src/main/java/com/flab/jbly/domain/user/PasswordEncoder.java
  src/main/java/com/flab/jbly/domain/user/User.java
  src/main/java/com/flab/jbly/domain/user/UserRepository.java
  src/main/java/com/flab/jbly/infra/common/ResponseEntityConstants.java
  src/main/java/com/flab/jbly/infra/encryption/PasswordEncoderImpl.java
  src/main/java/com/flab/jbly/infra/exception/ErrorCode.java
  src/main/java/com/flab/jbly/infra/exception/ErrorResponse.java
  src/main/java/com/flab/jbly/infra/exception/GlobalExceptionHandler.java
  src/main/java/com/flab/jbly/infra/exception/user/DuplicatedUserException.java
  src/main/java/com/flab/jbly/infra/exception/user/EncoderNoSuchAlgorithmException.java
  src/main/java/com/flab/jbly/infra/jpa/UserJpaRepository.java
  src/main/java/com/flab/jbly/infra/jpa/UserRepositoryAdapter.java
  src/main/java/com/flab/jbly/presentation/controller/user/UserController.java
  src/main/java/com/flab/jbly/presentation/request/UserSignUpRequest.java
  src/main/resources/application.yml
  src/main/resources/db/schema.sql
Labels: feat

#23 [#21] Github Action을 이용한 CI환경 구축
  .github/workflows/gradle.yml
  gradlew
  src/test/java/com/flab/jbly/JblyApplicationTests.java
  src/test/java/com/flab/jbly/infrastructure/.gitkeep
Labels: chore

#25 [#21] Github-Action을 이용한 CI구축
  .github/workflows/gradle.yml
Labels: chore

#28 [#12] crawling 을 위한 python 개발 환경 구축
  crawling/dbConnection/MysqlConnect.py
  crawling/dbConnection/__init__.py
  crawling/dbConnection/__pycache__/MysqlConnect.cpython-39.pyc
  crawling/dbConnection/__pycache__/__init__.cpython-39.pyc
  crawling/main.py
  crawling/parsing/WebCrawling.py
  crawling/parsing/__init__.py
  crawling/parsing/__pycache__/WebCrawling.cpython-39.pyc
  crawling/parsing/__pycache__/__init__.cpython-39.pyc
Labels: chore

#27 [#16] 프론트 구현을 위한 React연동
  src/main/java/com/flab/jbly/JblyApplication.java
Labels: chore

#33 [#16] reactfront file update
  frontend/reactfront/.gitignore
  frontend/reactfront/README.md
  frontend/reactfront/package-lock.json
  frontend/reactfront/package.json
  frontend/reactfront/public/favicon.ico
  frontend/reactfront/public/index.html
  frontend/reactfront/public/logo192.png
  frontend/reactfront/public/logo512.png
  frontend/reactfront/public/manifest.json
  frontend/reactfront/public/robots.txt
  frontend/reactfront/resources/asset-manifest.json
  frontend/reactfront/resources/favicon.ico
  frontend/reactfront/resources/index.html
  frontend/reactfront/resources/logo192.png
  frontend/reactfront/resources/logo512.png
  frontend/reactfront/resources/manifest.json
  frontend/reactfront/resources/robots.txt
  frontend/reactfront/resources/static/asset-manifest.json
  frontend/reactfront/resources/static/css/main.073c9b0a.css
  frontend/reactfront/resources/static/css/main.073c9b0a.css.map
  frontend/reactfront/resources/static/favicon.ico
  frontend/reactfront/resources/static/index.html
  frontend/reactfront/resources/static/js/787.0451fb7f.chunk.js
  frontend/reactfront/resources/static/js/787.0451fb7f.chunk.js.map
  frontend/reactfront/resources/static/js/main.d66186e7.js
  frontend/reactfront/resources/static/js/main.d66186e7.js.LICENSE.txt
  frontend/reactfront/resources/static/js/main.d66186e7.js.map
  frontend/reactfront/resources/static/logo192.png
  frontend/reactfront/resources/static/logo512.png
  frontend/reactfront/resources/static/manifest.json
  frontend/reactfront/resources/static/media/logo.6ce24c58023cc2f8fd88fe9d219db6c6.svg
  frontend/reactfront/resources/static/robots.txt
  frontend/reactfront/resources/static/static/css/main.073c9b0a.css
  frontend/reactfront/resources/static/static/css/main.073c9b0a.css.map
  frontend/reactfront/resources/static/static/js/787.0451fb7f.chunk.js
  frontend/reactfront/resources/static/static/js/787.0451fb7f.chunk.js.map
  frontend/reactfront/resources/static/static/js/main.d66186e7.js
  frontend/reactfront/resources/static/static/js/main.d66186e7.js.LICENSE.txt
  frontend/reactfront/resources/static/static/js/main.d66186e7.js.map
  frontend/reactfront/resources/static/static/media/logo.6ce24c58023cc2f8fd88fe9d219db6c6.svg
  frontend/reactfront/src/App.css
  frontend/reactfront/src/App.js
  frontend/reactfront/src/App.test.js
  frontend/reactfront/src/index.css
  frontend/reactfront/src/index.js
  frontend/reactfront/src/logo.svg
  frontend/reactfront/src/reportWebVitals.js
  frontend/reactfront/src/setupTests.js
Labels: chore

#38 [#29] Site Porterna crawling
  crawling/main.py
  crawling/parsing/MoreCherrySiteCrawling.py
  crawling/parsing/PorternaSiteCrawling.py
  crawling/parsing/__pycache__/PorternaSiteCrawling.cpython-39.pyc
  src/main/java/com/flab/jbly/JblyApplication.java
Labels: feat, crawling

#42 [#39] Crawling 대상 사이트에서 얻은 데이터 local DB에 저장
  crawling/dbConnection/MysqlConnect.py
  crawling/dbConnection/__pycache__/MysqlConnect.cpython-39.pyc
  crawling/main.py
  crawling/parsing/MoreCherrySiteCrawling.py
  crawling/parsing/PorternaSiteCrawling.py
  crawling/parsing/__pycache__/MoreCherrySiteCrawling.cpython-39.pyc
  crawling/parsing/__pycache__/PorternaSiteCrawling.cpython-39.pyc
Labels: feat

#44 [#41] Frontend React Login 구현
  frontend/reactfront/src/ApiService.js
  frontend/reactfront/src/App.js
  frontend/reactfront/src/component/Home.js
  frontend/reactfront/src/component/LoginForm.jsx
  frontend/reactfront/src/component/ProductListPage.jsx
  frontend/reactfront/src/component/SignUpForm.jsx
  frontend/reactfront/src/page/SignUpPage.jsx
Labels: feat
